version: "4"
services:
    backend:
    build: ./webserver/
    ports:
      - "3000:3000"
    volumes:
      - ./webserver:/src/webserver
      - /src/webserver/node_modules/
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    command: npm start
    restart: always
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
      MONGO_DB: "mongodb://mongodb:27017/irrigation"

  mongodb:
    image: mongo
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"
    restart: always
